### ISSUE TITLE
麻烦各位大佬辛苦看下这个，win 11系统，装了vc2019, cuda ，cudnn，torch，还是不行，报这个错误

### ISSUE THREAD

**Issue by 13051603700** [waityousea/xuniren#12]
C:\Users\Administrator\Desktop\xuniren> pip install .\freqencoder\
Processing c:\users\administrator\desktop\xuniren\freqencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: freqencoder
  Building wheel for freqencoder (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\Desktop\xuniren\freqencoder\setup.py", line 33, in <module>
          setup(
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 485, in build_extensions
          compiler_name, compiler_version = self._check_abi()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 875, in _check_abi
          raise UserWarning(msg)
      UserWarning: It seems that the VC environment is activated but DISTUTILS_USE_SDK is not set.This may lead to multiple activations of the VC env.Please set `DISTUTILS_USE_SDK=1` and try again.
      [end of output]

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for freqencoder
  Running setup.py clean for freqencoder
Failed to build freqencoder
ERROR: Could not build wheels for freqencoder, which is required to install pyproject.toml-based projects

**Comment by cscodeteam** [comment]
我也碰到了，你解决了吗

**Comment by newnob6** [comment]
我也是这个错误。急求解。

**Comment by jackyhwei** [comment]
x86 Native Tools Command Prompt for VS 2017切换到你的虚拟环境后，你需要先执行

**Comment by Qingshan0153** [comment]
[2D数字人安装文档.docx](https://github.com/waityousea/xuniren/files/14173756/2D.docx)

**Comment by Qingshan0153** [comment]
> [2D数字人安装文档.docx](https://github.com/waityousea/xuniren/files/14173756/2D.docx)

这是我自己整理的可以试试
