### ISSUE TITLE
windows 11 运行 python app.py 报错 ModuleNotFoundError: No module named '_raymarching_face'

### ISSUE THREAD

**Issue by QzLiny** [waityousea/xuniren#19]
PS D:\project\individual\digital-human\xuniren> python app.py
Traceback (most recent call last):
  File "D:\project\individual\digital-human\xuniren\raymarching\raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\individual\digital-human\xuniren\app.py", line 10, in <module>
    from tools import audio_pre_process, video_pre_process, generate_video,audio_process
  File "D:\project\individual\digital-human\xuniren\tools.py", line 20, in <module>
    from nerf.network import NeRFNetwork
  File "D:\project\individual\digital-human\xuniren\nerf\network.py", line 7, in <module>
    from .renderer import NeRFRenderer
  File "D:\project\individual\digital-human\xuniren\nerf\renderer.py", line 10, in <module>
    import raymarching
  File "D:\project\individual\digital-human\xuniren\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "D:\project\individual\digital-human\xuniren\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "D:\project\individual\digital-human\xuniren\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
  File "D:\Users\Hyacinth\anaconda3\envs\xuniren\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "D:\Users\Hyacinth\anaconda3\envs\xuniren\lib\site-packages\torch\utils\cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Users\Hyacinth\anaconda3\envs\xuniren\lib\site-packages\torch\utils\cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing _raymarching_face: 找不到指定的模块。

**Comment by liujin163** [comment]
工程根目录下运行：pip install ./raymarching 安装应该就可以解决这个问题

**Comment by langzizhixin** [comment]
pytorch和pytorch3d版本不对应，造成的报错。

**Comment by chenbjwbh** [comment]
> 工程根目录下运行：pip install ./raymarching 安装应该就可以解决这个问题

您好，按照您的pip install ./raymarching 报错，  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for raymarching-face
  Running setup.py clean for raymarching-face
Failed to build raymarching-face
ERROR: Could not build wheels for raymarching-face, which is required to install pyproject.toml-based projects
请您帮忙给指导以下。

**Comment by lmw0320** [comment]
> > 工程根目录下运行：pip install ./raymarching 安装应该就可以解决这个问题
> 
> 您好，按照您的pip install ./raymarching 报错， note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for raymarching-face Running setup.py clean for raymarching-face Failed to build raymarching-face ERROR: Could not build wheels for raymarching-face, which is required to install pyproject.toml-based projects 请您帮忙给指导以下。

请问你解决了么？？ 我也遇到相同的情况。。

**Comment by selfevolv** [comment]
+1

**Comment by ChengsongLu** [comment]
+1

**Comment by tranthuhoai3786** [comment]
> 工程根目录下运行：pip install ./raymarching� 安装应该就可以解决这个问题

i get the same error, do you have any solution? @chenbjwbh @lmw0320

**Comment by jackysong2009** [comment]
pip install ./raymarching
执行成功。
(Vach) PS D:\Metahuman\Vach\talkers\er_nerf> pip install ./raymarching
Processing d:\metahuman\vach\talkers\er_nerf\raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching_face
  Building wheel for raymarching_face (setup.py) ... done
  Created wheel for raymarching_face: filename=raymarching_face-0.0.0-cp310-cp310-win_amd64.whl size=241161 sha256=7a574e6697ac382f2341fc987443460453e4e6f12e158d6a9456a595ddae065c
  Stored in directory: C:\Users\15833\AppData\Local\Temp\pip-ephem-wheel-cache-5_q_wiiu\wheels\bb\6d\52\19643e7715cd22b429ac110109e8eabf1f49d338db50bb6625
Successfully built raymarching_face
Installing collected packages: raymarching_face
  Attempting uninstall: raymarching_face
    Found existing installation: raymarching_face 0.0.0
    Uninstalling raymarching_face-0.0.0:
      Successfully uninstalled raymarching_face-0.0.0
Successfully installed raymarching_face-0.0.0
但是执行训练，python main.py data/obama/ --workspace trial_obama/ -O --test --ckpt trial_obama/checkpoints/ngp.pth
报错信息如下：
Traceback (most recent call last):
  File "D:\Metahuman\Vach\talkers\er_nerf\main.py", line 6, in <module>
    from nerf_triplane.network import NeRFNetwork
  File "D:\Metahuman\Vach\talkers\er_nerf\nerf_triplane\network.py", line 5, in <module>
    from .renderer import NeRFRenderer
  File "D:\Metahuman\Vach\talkers\er_nerf\nerf_triplane\renderer.py", line 10, in <module>
    from .. import raymarching
ImportError: attempted relative import beyond top-level package
请问有人解决了吗？
