### ISSUE TITLE
求助 app.py websocket连接错误

### ISSUE THREAD

**Issue by huzhangNB** [waityousea/xuniren#22]
Traceback (most recent call last):
  File "C:\Users\XXXXXXX\.conda\envs\torch3d\lib\site-packages\gevent\pywsgi.py", line 988, in handle_one_response
    self.run_application()
  File "C:\Users\XXXXXXX\.conda\envs\torch3d\lib\site-packages\geventwebsocket\handler.py", line 75, in run_application
    self.run_websocket()
  File "C:\Users\XXXXXXX\.conda\envs\torch3d\lib\site-packages\geventwebsocket\handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "C:\Users\XXXXXXX\.conda\envs\torch3d\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\XXXXXXX\.conda\envs\torch3d\lib\site-packages\flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "C:\Users\XXXXXXX\.conda\envs\torch3d\lib\site-packages\werkzeug\routing\map.py", line 653, in match
    raise WebsocketMismatch() from None
werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2023-08-17T10:43:19Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '52284', 'HTTP_HOST': '127.0.0.1:8800', (hidden keys: 30)} failed with WebsocketMismatch

**Comment by Ikaros-521** [comment]
加一！！！！

**Comment by xxm1668** [comment]
+1

**Comment by weichampion** [comment]
Flask版本的问题，降级一下就ok，你们谁有data目录下的audio文件？

**Comment by Qingshan0153** [comment]
这个帖子可以解决 -- https://zhuanlan.zhihu.com/p/677917890
