### ISSUE TITLE
windows 安装是都在conda下面操作的的?

### ISSUE THREAD

**Issue by tddevrtx4090** [waityousea/xuniren#3]

**Comment by tddevrtx4090** [comment]
![image](https://github.com/waityousea/xuniren/assets/125423618/e4650058-0a59-4e17-a06a-024ee778e698)
这块是可选的安装步骤？直接跳过这块执行 `python app.py`也是报错
```
D:\FayProject\xuniren>C:\ProgramData\Anaconda3\envs\pytorch3d\python.exe app.py
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6'
Traceback (most recent call last):
  File "D:\FayProject\xuniren\raymarching\raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FayProject\xuniren\app.py", line 10, in <module>
    from tools import audio_pre_process, video_pre_process, generate_video,audio_process
  File "D:\FayProject\xuniren\tools.py", line 20, in <module>
    from nerf.network import NeRFNetwork
  File "D:\FayProject\xuniren\nerf\network.py", line 7, in <module>
    from .renderer import NeRFRenderer
  File "D:\FayProject\xuniren\nerf\renderer.py", line 10, in <module>
    import raymarching
  File "D:\FayProject\xuniren\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "D:\FayProject\xuniren\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "D:\FayProject\xuniren\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
  File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1610, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 2014, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1780, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```

**Comment by dengtianbi** [comment]
请问这个问题解决了吗，我目前也遇到这个问题

**Comment by xzl1996** [comment]
请问有解决吗，我也遇到了这个问题

**Comment by jackyhwei** [comment]
我这边freqencoder和shencoder两个都编译安装成功，但是gridencoder过不去，报的atomicAdd参数不匹配的错误，我尝试：
1. 增加多个atomicAdd空的inline接口，不行；
2. 改gencode=arch参数，不行；（我笔记本显卡是GeForce MX130，在NVIDIA官网https://developer.nvidia.com/cuda-gpus#collapseOne 上根本查不到）

不知道还有没有救

**Comment by ppppyg** [comment]
(make3d) D:\linye-project\code\3d_Reconstruction\Make-It-3D-master>pip install ./raymarching
Processing d:\linye-project\code\3d_reconstruction\make-it-3d-master\raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching
  Building wheel for raymarching (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [104 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building '_raymarching' extension
      creating D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38
      creating D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release
      creating D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project
      creating D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code
      creating D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction
      creating D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master
      creating D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching
      creating D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src
      Emitting ninja build file D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\TH -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\Anaconda\envs\make3d\include -ID:\Anaconda\envs\make3d\Include -c D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\bindings.cpp /FoD:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\bindings.obj /O2 /std:c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_raymarching -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: D:/linye-project/code/3d_Reconstruction/Make-It-3D-master/raymarching/build/temp.win-amd64-cpython-38/Release/linye-project/code/3d_Reconstruction/Make-It-3D-master/raymarching/src/bindings.obj
      cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\TH -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\Anaconda\envs\make3d\include -ID:\Anaconda\envs\make3d\Include -c D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\bindings.cpp /FoD:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\bindings.obj /O2 /std:c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_raymarching -D_GLIBCXX_USE_CXX11_ABI=0
      注意: 包含文件:  D:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch/extension.h
      注意: 包含文件:   D:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch\csrc\api\include\torch/all.h
      注意: 包含文件:    D:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h
      注意: 包含文件:     D:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch/csrc/WindowsTorchApiMacro.h
      注意: 包含文件:      D:\Anaconda\envs\make3d\lib\site-packages\torch\include\c10/macros/Export.h
      注意: 包含文件:       D:\Anaconda\envs\make3d\lib\site-packages\torch\include\c10/macros/cmake_macros.h
      D:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: 无法打开包括文件: “cstdint”: No such file or directory
      [2/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --generate-dependencies-with-compile --dependency-output D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\raymarching.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\TH -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\Anaconda\envs\make3d\include -ID:\Anaconda\envs\make3d\Include -c D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\raymarching.cu -o D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\raymarching.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_raymarching -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: D:/linye-project/code/3d_Reconstruction/Make-It-3D-master/raymarching/build/temp.win-amd64-cpython-38/Release/linye-project/code/3d_Reconstruction/Make-It-3D-master/raymarching/src/raymarching.obj
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --generate-dependencies-with-compile --dependency-output D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\raymarching.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\TH -ID:\Anaconda\envs\make3d\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\Anaconda\envs\make3d\include -ID:\Anaconda\envs\make3d\Include -c D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\raymarching.cu -o D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\build\temp.win-amd64-cpython-38\Release\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\src\raymarching.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_raymarching -D_GLIBCXX_USE_CXX11_ABI=0
      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)

      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)

      cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF2_OPERATORS__”(用“/U__CUDA_NO_HALF2_OPERATORS__”)

      raymarching.cu

      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\crt/host_config.h(238): fatal error C1083: 无法打开包括文件: “crtdefs.h”: No such file or directory

      raymarching.cu

      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "D:\Anaconda\envs\make3d\lib\site-packages\torch\utils\cpp_extension.py", line 1717, in _run_ninja_build
          subprocess.run(
        File "D:\Anaconda\envs\make3d\lib\subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\linye-project\code\3d_Reconstruction\Make-It-3D-master\raymarching\setup.py", line 44, in <module>
          setup(
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\make3d\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "D:\Anaconda\envs\make3d\lib\site-packages\torch\utils\cpp_extension.py", line 735, in build_extensions
          build_ext.build_extensions(self)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "D:\Anaconda\envs\make3d\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "D:\Anaconda\envs\make3d\lib\site-packages\torch\utils\cpp_extension.py", line 708, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "D:\Anaconda\envs\make3d\lib\site-packages\torch\utils\cpp_extension.py", line 1399, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "D:\Anaconda\envs\make3d\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for raymarching
  Running setup.py clean for raymarching
Failed to build raymarching
ERROR: Could not build wheels for raymarching, which is required to install pyproject.toml-based projects

(make3d) D:\linye-project\code\3d_Reconstruction\Make-It-3D-master>pip list
Package                 Version
----------------------- ------------------
absl-py                 2.1.0
anyio                   3.7.1
argon2-cffi             23.1.0
argon2-cffi-bindings    21.2.0
attrs                   23.2.0
backcall                0.2.0
beautifulsoup4          4.12.3
bleach                  6.0.0
cachetools              5.3.3
certifi                 2024.2.2
cffi                    1.15.1
charset-normalizer      3.3.2
clip                    1.0
colorama                0.4.6
comm                    0.1.4
contextual-loss-pytorch 0.1.0
cycler                  0.11.0
dataclasses             0.8
dearpygui               1.10.1
debugpy                 1.7.0
decorator               5.1.1
defusedxml              0.7.1
diffusers               0.28.0.dev0
einops                  0.6.1
entrypoints             0.4
exceptiongroup          1.2.0
fastjsonschema          2.19.1
filelock                3.13.3
fonttools               4.38.0
fsspec                  2024.3.1
ftfy                    6.2.0
fvcore                  0.1.5.post20221221
google-auth             2.29.0
google-auth-oauthlib    0.4.6
grpcio                  1.62.1
huggingface_hub         0.23.0.dev0
idna                    3.6
imageio                 2.31.2
imageio-ffmpeg          0.4.9
importlib_metadata      7.1.0
importlib-resources     5.12.0
iopath                  0.1.10
ipykernel               6.16.2
ipython                 7.34.0
ipython-genutils        0.2.0
ipywidgets              8.1.2
jedi                    0.19.1
Jinja2                  3.1.3
joblib                  1.3.2
jsonschema              4.17.3
jupyter_client          7.4.9
jupyter_core            4.12.0
jupyter-server          1.24.0
jupyterlab-pygments     0.2.2
jupyterlab_widgets      3.0.10
kiwisolver              1.4.5
Markdown                3.4.4
markdown-it-py          2.2.0
MarkupSafe              2.1.5
matplotlib              3.5.3
matplotlib-inline       0.1.6
mdurl                   0.1.2
mistune                 3.0.2
nbclassic               1.0.0
nbclient                0.7.4
nbconvert               7.6.0
nbformat                5.8.0
nest-asyncio            1.6.0
ninja                   1.11.1.1
notebook                6.5.6
notebook_shim           0.2.4
numpy                   1.22.4
oauthlib                3.2.2
open3d                  0.10.0.0
opencv-python           4.9.0.80
packaging               24.0
pandas                  1.3.5
pandocfilters           1.5.1
parso                   0.8.4
pickleshare             0.7.5
pillow                  10.3.0
pip                     23.3.1
pkgutil_resolve_name    1.3.10
portalocker             2.8.2
prometheus-client       0.17.1
prompt-toolkit          3.0.43
protobuf                3.20.3
psutil                  5.9.8
pyasn1                  0.5.1
pyasn1-modules          0.3.0
pycparser               2.21
Pygments                2.17.2
PyMCubes                0.1.4
pyparsing               3.1.2
pyproject               1.3.1
pyrsistent              0.19.3
python-dateutil         2.9.0.post0
pytorch3d               0.7.6
pytz                    2024.1
pywin32                 306
pywinpty                2.0.10
PyYAML                  6.0.1
pyzmq                   24.0.1
regex                   2023.12.25
requests                2.31.0
requests-oauthlib       2.0.0
rich                    13.7.1
rsa                     4.9
safetensors             0.4.2
scikit-learn            1.0.2
scipy                   1.7.3
Send2Trash              1.8.3
setuptools              68.2.2
six                     1.16.0
sniffio                 1.3.1
soupsieve               2.4.1
tabulate                0.9.0
tensorboard             2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorboardX            2.6.2.2
termcolor               2.4.0
terminado               0.17.1
threadpoolctl           3.1.0
timm                    0.9.12
tinycss2                1.2.1
tinycudann              1.7
torch                   1.10.0+cu113
torch-ema               0.3
torchaudio              0.10.0+cu113
torchmetrics            0.11.4
torchvision             0.11.1+cu113
tornado                 6.2
tqdm                    4.66.2
traitlets               5.9.0
trimesh                 4.2.4
typing_extensions       4.11.0
urllib3                 2.2.1
wcwidth                 0.2.13
webencodings            0.5.1
websocket-client        1.6.1
Werkzeug                2.2.3
wheel                   0.37.1
widgetsnbextension      4.0.10
xatlas                  0.0.9
yacs                    0.1.8
zipp                    3.18.1
